services:
  web:
    container_name: nette_web
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - VIRTUAL_HOST=localhost
    networks:
      - nette_net
    build:
      context: .
      dockerfile: docker/Dockerfile

  db:
    env_file:
      - .env
    image: mysql:8.0
    container_name: nette_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nette_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      #- ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nette_net
  phpmyadmin:
    env_file:
      - .env
    container_name: nette_pma
    image: phpmyadmin
    networks:
      - nette_net
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - "8888:80"
    restart: always

volumes:
  db_data:

networks:
  nette_net: